Enable the reference equality test
This fixes a spooky bug caused by a reflective calls to ExtendJ's
ASTNode attributes. When running from jar, there was a single copy
of the Beaver runtime library and everything was fine. When running
from JUnit, calls to Symbol.clone() coming from ASTNode.clone()
were throwing NoSuchMethodError which are silently dropped when
handling ReflectiveOperationException.